---
title: "Data Import"
output: github_document
---

## CSV FILES

```{r tidyverse, message = FALSE}
library(tidyverse)
```

#### Read in data

Read in the litters dataset

```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```


#### Look at the data

Printing in the console
```{r}
litters_df
```

```{r}
head(litters_df)
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```

alternatively: enter in console
View(litters_df)

#### Options to read_csv
?read_csv

```{r}
litters_df2 = read_csv("./data_import_examples/FAS_litters.csv", 
                      skip = 10, 
                      col_names = FALSE,
                      na = c("", "NA", ".", 999))
```


## EXCEL FILES

Read in an excel file

```{r}
library(readxl)
mlb_df = read_excel("./data_import_examples/mlb11.xlsx")
mlb_df
```

#### Excel specific options

?read_excel

Take note of sheet and range options. 

```{r}
mlb_df2 = read_excel("./data_import_examples/mlb11.xlsx", range = "A1:F7")
```


## SAS FILES

Read in a SAS file

```{r}
library(haven)
pulse_df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
pulse_df 
```

Take note of names and clean.








