---
title: "Tidy Data"
output: github_document
---

```{r tidyverse, message = FALSE}
library(tidyverse)
```

## pivot_longer

Load the PULSE data

```{r}
pulse_data =
    haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
    janitor::clean_names()
```

Wide format to long format

```{r}
pulse_data_tidy = 
    pulse_data %>% 
    pivot_longer(
      bdi_score_bl:bdi_score_12m,
      names_to = "visit",
      names_prefix = "bdi_score_",
      values_to = "bdi"
    )
```

rewrite, combine, and extend
```{r}
pulse_data =
    haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>% 
    janitor::clean_names() %>% 
    pivot_longer(
      bdi_score_bl:bdi_score_12m,
      names_to = "visit",
      names_prefix = "bdi_score_",
      values_to = "bdi"
    ) %>%
    relocate(id, visit) %>% 
    mutate(visit = recode(visit, "bl" = "00m"))
```

## pivot_wider

Make up data

```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )
```

```{r}
analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
```

## Binding Rows

Using LOR data

First step: Import each table

```{r}
fellowship = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship")

two_towers = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")
  
  return_king = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```

Bind all the rows together

```{r}
lotr_tidy = 
  bind_rows(fellowship, two_towers, return_king) %>% 
  janitor::clean_names() %>%
  relocate(movie) %>%
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words"
  )
```

## Joining Datasets

Import and clean the FAS datasets

```{r}
pups_df = 
  read_csv("./data_import_examples/FAS_pups.csv") %>% 
  janitor::clean_names() %>% 
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))

litters_df =
   read_csv("./data_import_examples/FAS_litters.csv") %>% 
   janitor::clean_names() %>%
   relocate(litter_number) %>% 
   separate(group, into = c("dose", "day_of_tx"), sep = 3)
```

Join datasets

```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") %>% 
  arrange(litter_number) %>% 
  relocate(litter_number, dose, day_of_tx)
```

























